name: 'CI/CD'

on:
  push:
    branches: 
      - "master"
  workflow_dispatch:
    

jobs:
  docker-build:
    runs-on: 
      - ubuntu-latest

    steps:
      - name: "Git clone"
        uses: actions/checkout@v4.1.1
     
      - name: "Docker build"
        uses: docker/build-push-action@v5.3.0
        with: 
          context: "."
          tags: "go-todo"
          file: "Dockerfile"
          
      - name: "docker login"
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: arturgrigoryan1/github-action-example:go-todo
      
    
     
            
          
    
