name: 'CI/CD'

on:
  push:
    branches: 
      - "master"

jobs:
  hello-world:
    runs-on: 
      - ubuntu-latest

    steps:
      - name: "Git clone"
        uses: actions/checkout@v4.1.1
        
      - name: "List current folder"
        run : ls -la

      - name: "Docker build"
        uses: docker/build-push-action@v5.3.0
        with: 
          context: "."
          tags: "$go-todo"
          file: "Dockerfile"
          
    
